### PR TITLE
typo

### PR DESCRIPTION
**Pull request by tarcnux**

### CODE REVIEW

**Comment by tarcnux** [comment]
Now I see that a have colaborator permission in Coggle, maybe I have done something wrong. Review this pull request carefully or reject it, please. I will take more attention to not work directly in Coggle/translation rather Tarcnux/Translations

**Comment by tarcnux** [comment]
Maybe it's a good idea reject this pull request! I send another.

**Comment by autopulated** [comment]
This looks good!

I made some pull requests of my own, and merged them after I merged your previous changes. The merge conflict is because you didn't pull those changes to your repository before making more changes. You can do this by:

```
git remote add upstream git@github.com:Coggle/translations.git
git pull upstream master
```

Which should merge the latest changes from the Coggle repository (upstream) into your own fork.

Hope that makes sense – in any case, your new changes look good to me and I'm going to merge :)

**Comment by tarcnux** [comment]
Nice! This is what I intended to ask you how to do, now it's ok! Let's back to work.

**Pull request merged**
